### ISSUE TITLE
Failed to load config "airbnb-typescript" to extend from

### ISSUE THREAD

**Issue by pavelee** [Tim-W-James/eslint-config#1]
Hey, 

I tried to install and checkout, unfortunately it failed on command `next lint`

Error:
Failed to load config "airbnb-typescript" to extend from.
Referenced from: /path_to_project/node_modules/@tim-w-james/eslint-config/index.js
error: script "lint" exited with code 1 (SIGHUP)

**Comment by Tim-W-James** [comment]
Would you be able to check if you've installed all required peer-dependencies? In this case, `eslint-config-airbnb` and `eslint-config-airbnb-typescript`?

**Comment by Tim-W-James** [comment]
I've updated the [installation instructions](https://github.com/Tim-W-James/eslint-config#install) to make the required peer-deps more clear.

**Comment by pavelee** [comment]
sorry, I forgot to response! Thank you, now it's clear ❤️
